<?php
$translate = $this->plugin('translate');
// Prepare the property queries.
$properties = isset($query['property']) ? $query['property'] : [];
$properties = array_filter($properties, function ($value) {
  return isset($value['text']) ? '' !== trim($value['text']) : true;
});
if (!$properties) {
  $properties[] = [];
}

if (isset($query['search'])) {
  unset($properties[0]['joiner']);
  array_unshift($properties, [
    'property' => '',
    'type' => 'in',
    'text' => $query['search']
  ]);
}
$search_id = $this->siteSetting('search_main_page');
$searchPage = $this->api()->read('search_pages', $search_id)->getContent();
$adapter = $searchPage->index()->adapter();
$facetFields = $adapter->getAvailableFacetFields($searchPage->index());

$fields_to_use = [
  'dcterms_title_t',
  'dcterms_contributor_t',
  'dcterms_creator_s',
  'dcterms_temporal_dt',
  'dcterms_description_t',
  'dcterms_publisher_t',
  'dcterms_subject_s',
  'dcterms_spatial_t',
  'dcterms_temporal_dt',
  'dcterms_type_s',
];


$facetFields = array_intersect_key($facetFields,array_flip($fields_to_use));

$queryOption = function ($value, array $search, $key, $text) {
  $selected = null;
  if (isset($search[$key]) && $value === $search[$key]) {
    $selected = ' selected';
  }
  return sprintf('<option value="%s"%s>%s</option>', $value, $selected, $text);
};
$queryText = function (array $search, $index) {
  $text = isset($search['text']) ? $search['text'] : null;
  return sprintf('<input type="text" class="query-text" name="%s" value="%s" aria-label="%s">',
    $this->escapeHtml("property[$index][text]"),
    $this->escapeHtml($text),
    $this->escapeHtml($this->translate('Query text')));
}
?>
<!-- TEMPLATE BEGIN common/advanced-search/properties -->

<div id="property-queries" class="field removable multi-value" role="group" aria-labelledby="by-value-label">
    <div class="field-meta">
        <span id="by-value-label"
              class="label"><?php echo $translate('Search by <span class="emphasized-text">value</span>'); ?></span>
    </div>
    <div class="inputs">
      <?php
      $index = 0;
      foreach ($properties as $property):
        $stem = "property[$index]";
        ?>
          <div class="value">
              <select class="joiner" name="<?php echo $this->escapeHtml($stem . '[joiner]'); ?>">
                <?php echo $queryOption(' ', $property, 'joiner', $translate('Or')); ?>
                <?php echo $queryOption('+', $property, 'type', $translate('Must contain')); ?>
                <?php echo $queryOption('-', $property, 'type', $translate('Must not contain')); ?>
              </select>

              <select class="query-type" name="<?php echo $this->escapeHtml($stem . '[type]'); ?>"
                      aria-label="<?php echo $translate('Query type'); ?>">


                <?php
                foreach ($facetFields as $facetField) {
                  echo $queryOption($facetField['name'], $property, 'type', $translate($facetField['label']));
                }

                ?>

              </select>

            <?php echo $queryText($property, $index); ?>
              <button type="button" class="remove-value button"><?php echo $translate('Remove'); ?></button>
          </div>
        <?php
        $index++;
      endforeach;
      echo $this->hyperlink($translate('Additional Value Search'), '#', ['class' => 'add-value button']);
      ?>
    </div>
</div>
<!-- TEMPLATE END common/advanced-search/properties -->
