<?php
$translate = $this->plugin('translate');
// Prepare the item set queries
$ids = isset($query['item_set_id']) ? $query['item_set_id'] : [];
if (!is_array($ids)) {
    $ids = [$ids];
}
$ids = array_filter($ids);
if (!$ids) {
    $ids = [null];
}
?>
<!-- BEGIN TEMPLATE: /common/advanced-search/item-sets.phtml -->
<div id="item-sets" class="field removable multi-value" role="group">
    <div class="field-meta">
        <span id="by-item-set-label" class="label"><?php echo $translate('Search by <span class="emphasized-text">Collection</span>'); ?></span>
        <?php echo $this->hyperlink('', '#', ['class' => 'expand', 'title' => $translate('Expand')]); ?>
        <div class="collapsible">
            <div class="field-description"><?php echo $translate('Searches for items that are assigned to any of these collections.'); ?></div>
        </div>
    </div>
    <div class="inputs">
        <?php foreach ($ids as $id): ?>
        <div class="value">
            <?php echo $this->itemSetSelect([
                'name' => 'item_set_id[]',
                'attributes' => [
                    'value' => $id,
                    'aria-labelledby' =>  'by-item-set-label'
                ],
                'options' => [
                    'empty_option' => '[Select Collection]',
                    'disable_group_by_owner' => $this->status()->isSiteRequest(),
                ],
            ]); ?>
            <button type="button" class="remove-value button"><?php echo $translate('Remove'); ?></button>
        </div>
        <?php endforeach; ?>
        <a href="#" class="add-value button"><?php echo $translate('Additional Value Search'); ?></a>
    </div>
</div>
<!-- END TEMPLATE: /common/advanced-search/item-sets.phtml -->
