<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$dateHandler = $this->plugin('dateHandler');
$labelInfo = $this->setting('property_label_information');
$searchMainPage = $this->siteSetting('advancedsearch_main_config');
/** @var  \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig */
$searchConfig = $this->api()->searchOne('search_configs', ['id' => $searchMainPage])->getContent();
$searchPath = $searchConfig->siteUrl();

?>
<!-- BEGIN common/resource-values.phtml -->
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property" data-term="<?php echo $escape($term); ?>" >
        <div class="metadata-label">
            <?php if ($propertyData['alternate_label']): ?>
                <?php echo $escape($propertyData['alternate_label']); ?>
            <?php else: ?>
                <?php echo $escape($translate($propertyData['property']->label())); ?>
            <?php endif; ?>
            <?php if ('term' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
            <?php elseif ('vocab' === $labelInfo): ?>
                <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
            <?php endif; ?>
        </div>
        <div class="values">
            <?php
            /** @var \Omeka\Api\Representation\ValueRepresentation $value */
            foreach ($propertyData['values'] as $value):
                $valueType = $value->type();
                $term = $propertyData['property']->term(); // dcterm:termname
                $value_label = $value->__toString();
                $class = ['value'];
                $url =  $searchConfig->siteUrl(). "?facet" . urlencode("[") . $term . urlencode("][0]") . "=" . urlencode($value_label);

                if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                    $class[] = 'resource';
                    $class[] = $escape($value->valueResource()->resourceName());
                    $valueRepresentation = $value->valueResource()->valueRepresentation();

                    // Use supplied url if available
                    if ($valueRepresentation && array_key_exists('url',$valueRepresentation)) {
                        $url = $valueRepresentation['url'];
                    }

                    // Use display title if available.
                    if ($valueRepresentation && array_key_exists('display_title',$valueRepresentation)) {
                        $value_label = $valueRepresentation['display_title'];
                    }

                } elseif ('uri' == $valueType) {
                    $class[] = 'uri';
                }
                if (!$value->isPublic()) {
                    $class[] = 'private';
                }

                // Convert dates

                if ($dateHandler->isDate($value)) {
                    $value_label = $dateHandler->render($value);
                }

                ?>
                <div class="<?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                    <a class='subject-title' href='<?= $url ?>'><?= $value_label ?></a>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
<!-- END common/resource-values.phtml -->
