<?php
$translate = $this->plugin('translate');
$prevText = $translate('Prev');
$nextText = $translate('Next');
?>
<?php if ($prevPage || $nextPage): ?>
  <div class="site-page-pagination">
    <?= $prevPage ? $this->hyperlink($prevText, $prevPage->siteUrl(),['class'=>'previous']) : ''; ?>
    <?= $nextPage ? $this->hyperlink($nextText, $nextPage->siteUrl(),['class'=>'next']) : ''; ?>
  </div>
<?php endif; ?>
