<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');

if (!isset($sortBy)) {

    // Weird that this happens here. The values don't seem to be passed in browse.phtml, but also there are no
    // default values in that instance.

    $sortBy = [
      [
        'label' => $translate('Sort by Title'),
        'value' => 'dcterms:title'
      ],
      [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
      ],
      [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
      ],
      [
        'label' => $translate('Sort by Date'),
        'value' => 'created'
      ],
    ];

}
?>
<form class="sorting" action="">
    <?php echo $this->queryToHiddenInputs(['sort_by', 'sort_order']); ?>
    <select name="sort_by" aria-label="<?php echo $translate('Sort by'); ?>">
        <?php foreach($sortBy as $sortByHeading): ?>
            <?php $selected = ($sortByQuery === $sortByHeading['value']) ? 'selected' : ''; ?>
            <option value="<?php echo $escape($sortByHeading['value']); ?>" <?php echo $selected; ?>><?php echo $sortByHeading['label']; ?></option>
        <?php endforeach; ?>
    </select>
    <div class="sort-block">
        <select name="sort_order" aria-label="<?php echo $translate('Sort order'); ?>">
            <option value="asc" <?php echo ($sortOrderQuery === 'asc') ? 'selected' : ''; ?>><?php echo $translate('Sort Ascending'); ?></option>
            <option value="desc" <?php echo ($sortOrderQuery === 'desc') ? 'selected' : ''; ?>><?php echo $translate('Sort Descending'); ?></option>
        </select>
        <button type="submit"><?php echo $translate('Sort'); ?></button>
    </div>
</form>
