<?php
  $translate = $this->plugin("translate");
  $escape = $this->plugin("escapeHtml");
  $partial = $this->plugin('partial');
  $this->htmlElement("body")->appendAttribute("class", "item resource show");
  $embedMedia = $this->siteSetting("item_media_embed", false);
  $itemMedia = $item->media();
  $oEmbed = $itemMedia && $itemMedia[0]->renderer() === 'oembed';

  $institution = !empty($item->value('vra:placeOfRepository')) ? $item->value('vra:placeOfRepository') : 'Item';
  $institutionClass = urlencode(strtolower(str_replace(' ','-',$institution)));
  $contentType = [];
  $contentType['value'] = ucfirst(!empty($item->value('dcterms:type')) ? $item->value('dcterms:type') : 'Item');

  $metadata_file_name = "metadata-" . urlencode(strtolower(str_replace(' ','_',$item->title()))) .".json";

  $relatedItems = [];
  $relatedProperties = ['dcterms:subject']; // Array of properties to find related items.

  foreach(array_intersect_key($item->values(),array_flip($relatedProperties)) as $term => $valueDetails) {
    foreach($valueDetails['values'] as $value) {
      // Prepare a search query to find items with the same property value
      $query = [
        'property' => [
          [
            'property' => $value->jsonSerialize()['property_id'],
            'type' => 'eq',
            'text' => $value->value(),
          ],
        ],
      ];
      $response = $this->api()->search('items',$query);
      foreach($response->getContent() as $itemRepresentation) {
        $id = $itemRepresentation->id();
        // Filter out the current item
        if ($id !== $item->id()) {
          // Remove duplicates by providing id as key
          $relatedItems[$id] = $itemRepresentation;
        }
      }
    }
  }
?>

<!-- BEGIN agile-theme-tools/agile-item/show.phtml -->

<?php $this->trigger("view.show.before"); ?>
<div class='item-container  <?= $institutionClass; ?>'>
  <div class='item-viewer'>
    <?php if ($this->universalViewer($item) && !$oEmbed):
      echo $this->universalViewer($item);
    elseif (($embedMedia && $itemMedia) || $oEmbed): ?>
      <div class="media-embeds">
        <?php foreach ($itemMedia as $media):
          echo $media->render();
        endforeach; ?>
      </div>
    <?php endif; ?>
  </div>
  <div class='item-info item-text'>
    <div class="wayfinding">
      <a href="<?php echo $site->siteUrl(); ?>"><img alt='Home Icon' class='wayfinding-home' src='<?php echo $this->assetUrl('img/svg/icons/home-grey.svg')?>'></a>
      <a href="<?php echo $site->siteUrl(); ?>/browse">Browse the collection</a>
    </div>
    <header>
      <div class="item-label"><?php echo((!empty($institution) ? $institution . ' | ' : '') . $contentType['value']); ?></div>
      <?php echo $this->pageTitle($item->displayTitle(), 1); ?>
    </header>
    <?php if ($item->value('dcterms:alternative')): ?>
      <div class='subtitle'>
        <?php echo($item->value('dcterms:alternative')); ?>
      </div>
    <?php endif; ?>
    
   
      <div class="container-with-tabs-and-panels">
      
        <div class="tabs">
          <a class="tab description-tab active-tab">Description</a> |
          <a class="tab info-tab">Transcription</a>
        </div>
        <div class="panels">
          <div class="description-panel">
              <p class="description-text">
              <?php $values = $item->value('dcterms:description', ['all' => true]); foreach ($values as $value) { echo $value->asHtml(); }?>
            </p>
            <div class='key-metadata'>
              <div class='metadata-list metadata-list-top'>
                <?php
                // Display key terms
                $keyTerms = ['dcterms:creator'=>'Creator','dcterms:date'=>'Date','dcterms:source'=>'Source','dcterms:format'=>'Format'];
                  foreach(array_intersect_key($item->values(),$keyTerms) as $term => $value):
                    if (!empty($value['values'][0])):
                      printf("<div class='property' data-term='%s'>\n",$term);
                      printf("   <div class='metadata-label'>%s</div>",!empty($value['alternate_label']) ? $value['alternate_label'] : $keyTerms[$term]);
                      print ("    <div class='values'>");
                      printf("       <div class='value'>%s</div>",$value['values'][0]);
                      print ("    </div>");
                      print ("</div>");
                      endif;
                  endforeach;
                ?>
                <div class="property">
                  <?php $itemSets = $item->itemSets(); ?>
                  <?php if (count($itemSets) > 0): ?>
                    <div class="label label-item-info metadata-label"><?php echo $translate(
                        "Item sets"
                      ); ?></div>
                    <?php foreach ($itemSets as $itemSet): ?>
                      <div class="value"><a class="item-set-link-top" href="<?php echo $escape(
                          $itemSet->url()
                        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                    <?php endforeach; ?>
                  <?php endif; ?>
                </div>
              </div>
            </div>
            <div class='rights'>
              <p class="metadata-label">Download</p>
              <div class=download-icons>
                <?php if ($item->primaryMedia()): ?>
                <div class='download-item'>
                  <?php
                  // See https://stackoverflow.com/a/64719808/16534002
                  $primary_media = $item->primaryMedia()->originalUrl();
                  $url_parts = $primary_media ? explode('/',$primary_media) : [];
                  $file_name = array_pop($url_parts);
                  $dl_attribute = !empty($file_name) ? ' download="'. $file_name .'"' : '';

                  ?>
                  <a class='icon-ui' title="Download item" href='<?php echo $item
                    ->primaryMedia()
                    ->originalUrl(); ?>' <?php echo $dl_attribute; ?>>
                    <span class="screen-reader-text">Download item</span>
                    Item
                  </a>
                </div>
                <?php endif; ?>
                <div class='download-metadata'>
                  <a class='icon-ui' title="Download metadata" target="_blank" type='application/json' href='<?php echo $item->apiUrl(); ?>' download='<?php echo $metadata_file_name; ?>'>
                    <span class="screen-reader-text">Download metadata</span>
                    Metadata
                  </a>
                </div>
              </div>
            </div>
            <?php if (!empty($item->value("dcterms:rights"))): ?>
              <div class='rights-statement'>
                <p class="metadata-label">Rights Statement</p>
                <p class="metadata-value"><?php echo($item->value('dcterms:rights')); ?></p>
              </div>
            <?php endif; ?>
          </div>
          <div class="transcription-panel">
            <p class="metadata-label">Transcription of this Item</p>
              <?php if (!empty($item->value("vra:text"))): ?>
              <?php echo $item->value("vra:text"); ?>
            <?php else: ?>
              <p class="no-transcription">Transcription not available.</p>
            <?php endif; ?>   
          </div>
        </div>
      </div>
  </div>
</div>
<div class='item-metadata-block'>
  <header>
    <h2>Full Metadata</h2>
  </header>
  
  <div class='metadata-list reversed'>
    <?php echo $item->displayValues(); ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <div class="metadata-label"><?php echo $translate("Item sets"); ?></div>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value"><a class="item-set-link" href="<?php echo $escape(
          $itemSet->url()
        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
  </div>

  <?php
    $page = $this->params()->fromQuery("page", 1);
    $property = $this->params()->fromQuery("property");
    //$subjectValues = $item->displaySubjectValues($page, 25, $property);
    $subjectValues = null; //@todo: getting error
  ?>
  <?php if ($subjectValues): ?>
    <div id="item-linked">
    <h3><?php echo $translate("Linked resources"); ?></h3>
    <?php echo $subjectValues; ?>
    </div>
  <?php endif; ?>
</div>
<?php if (count($relatedItems) > 0): ?>
  <div id="related-items">
    <h2>Related Items</h2>
    <ul class="masonry-grid cards grid">
      <?php foreach ($relatedItems as $relatedItem): ?>
        <?= $partial('agile-item/card', [
          'item' => $relatedItem,
          'containerElement' => 'li'
        ]) ?>
      <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
<!-- END agile-theme-tools/agile-item/show.phtml -->
