<?php
$plugins = $this->getHelperPluginManager();
$translate = $this->plugin("translate");
$escape = $this->plugin("escapeHtml");
$escapeAttr = $this->plugin('escapeHtmlAttr');
$partial = $this->plugin('partial');
$dateHandler = $this->plugin('dateHandler');
/** @var \AgileThemeTools\View\Helper\AgileSearchHelper $searchHelper */
$searchHelper = $this->plugin('agileSearchHelper');
$this->htmlElement("body")->appendAttribute("class", "item resource show");

// This is deprecated
$embedMedia = $this->siteSetting("item_media_embed", false);
$itemMedia = $item->media();
$hasMedia = $itemMedia && is_array($itemMedia) && count($itemMedia) > 0;
$hasTranscription = !empty($item->value("vra:text"));

$mirador = null;
$uv = null;

$contentType = [];
$contentType['value'] = ucfirst(!empty($item->value('dcterms:type')) ? $item->value('dcterms:type') : 'Item');

$metadata_file_name = "metadata-" . urlencode(strtolower(str_replace(' ','_',$item->title()))) .".json";

$relatedItems = [];
$relatedProperties = ['dcterms:subject']; // Array of properties to find related items.

/** @var \Omeka\Api\Representation\ValueRepresentation $temporal */
$temporal = $item->value('dcterms:temporal');
$year = $temporal ? $dateHandler->render($temporal->value(),'Y') : null;
$dateHandler->isDate($temporal);

$resourceClass = '';
$label = !empty($item->value('dcterms:type')) ? $item->value('dcterms:type') : 'Item';

$year = !empty($item->value('dcterms:temporal')) && is_array($item->value('dcterms:temporal')) && count($item->value('dcterms:temporal')) > 0 ? date('Y',$item->value('dcterms:temporal')[0]) : null;
$creator = $item->value('dcterms:creator');

if (method_exists($item,'resourceClass') && $item->resourceClass() !== null) {
  $resourceClass = $item->resourceClass();
  $resourceClassLabel = $item->resourceClass()->label();
  $resourceIndicator = "resource-id-" . $item->resourceClass()->id();
  $label = $resourceClassLabel;
}

// Terms to use in main description area. Format: $keyTerms = ['dcterms:termname'=>'Label to Use']

$keyTerms = ['dcterms:creator'=>'Creator','dcterms:date'=>'Date','dcterms:source'=>'Source','dcterms:format'=>'Format'];


$searchMainPage = $this->siteSetting('advancedsearch_main_config');
/** @var  \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig */
//$searchConfig = $this->api()->searchOne('search_configs', ['id' => $searchMainPage])->getContent();
$searchConfig = $plugins->get('getSearchConfig');
// Updated way of handling facets
$facetElements = $plugins->get('facetElements');
$facetParams = ['template'=>'search/facet-link'];

/** @var  \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchConfig2 */
/** @var  \Omeka\Controller\Site\  $site */

foreach(array_intersect_key($item->values(),array_flip($relatedProperties)) as $term => $valueDetails) {
  foreach($valueDetails['values'] as $value) {
    // Prepare a search query to find items with the same property value
    $query = [
      'property' => [
        [
          'property' => $value->jsonSerialize()['property_id'],
          'type' => 'eq',
          'text' => [$value->value()],
        ],
      ],
    ];
    $response = $this->api()->search('items',$query);
    $limit = 24;
    $i=1;
    foreach($response->getContent() as $itemRepresentation) {
      if ($i >= $limit) {
        continue;
      }
      $i++;
      $id = $itemRepresentation->id();
      // Filter out the current item
      if ($id !== $item->id()) {
        // Remove duplicates by providing id as key
        $relatedItems[$id] = $itemRepresentation;
      }
    }
  }
}

if ($hasMedia) {
  // Determine which viewer to use. Note that the UV and Mirador viewers are displayed via the blocks disposition module,
  // which does not give contextual control over which viewer to display. Viewer handling is now done via css
  // @todo: there must be a better way.

  // Check if UV plugin exists
  try {
    $uv = $this->plugin('universalViewer');
  } catch (Exception $exception) {
    $uv = null;
  }

  try {
    $mirador = $this->plugin('mirador');
  } catch (Exception $exception) {
    $mirador = null;
  }

  $oEmbed = $itemMedia && $itemMedia[0]->renderer() === 'oembed';
  $viewer = 'viewer-default';

  // PDF Viewer Support
  $source = $item->primaryMedia()->originalUrl();
  $mediaType = $item->primaryMedia()->mediaType();

  $uv_media = [
    'text',
    'moving image' // Use UV for video right now
  ];

  if($mediaType) {
    if ($mediaType === 'application/pdf') {
      $viewer = 'viewer-pdf';
    } elseif(strpos($mediaType,'video') > -1) {
      $viewer = 'viewer-video';
    } elseif ($uv && in_array(strtolower($label), $uv_media)) {
      $viewer = 'viewer-uv';
    } elseif ($mirador) {
      $viewer = 'viewer-mirador';
    }
  }

}
?>

<!-- BEGIN agile-theme-tools/agile-item/show.phtml -->

<?php $this->trigger("view.show.before"); ?>
<div class='item-container'>
  <div class='item-viewer <?= $viewer ?>'>
    <?php
    if ($hasMedia):
      // Default viewer
      if ($viewer === 'viewer-default' && (($itemMedia) || $oEmbed)): ?>
        <div class="media-embeds">
          <?php foreach ($itemMedia as $media):
            echo $media->render();
          endforeach; ?>
        </div>
      <?php
      elseif ($viewer === 'viewer-pdf'):
        $options = [];
        $options['attributes'] = 'allowfullscreen="allowfullscreen" zoom="page-fit"';
        ?>

        <object height="100%" width="100%" <?= $options['attributes'] ?> data="<?= $escapeAttr($source) ?>" type="<?= $mediaType ?>"></object>

      <?php
      elseif ($viewer === 'viewer-video' && $source):
        ?>
        <video width="100%" preload="auto" onclick="playPause();" controls="controls">
          <source src="<?= $escapeAttr($source) ?>"  type="<?= $mediaType ?>" />
        </video>
      <?php
      elseif ($mirador):
        echo $this->mirador($item);

      // This will display UV or other media players assigned to view.show.after.
      else:
        $this->trigger("view.show.after");
      endif;
    else:
      $this->trigger("view.show.after");
    endif;
    ?>
    <?php if (($mirador || $viewer === 'viewer-pdf' || $viewer === 'viewer-video') && !empty($item->value('dcterms:description'))): ?>
      <div id="viewer-support">
        <div class="label">Item description</div>
        <div id="viewer-description">
          <?= $item->value('dcterms:description') ?>
        </div>
      </div>
    <?php endif; ?>
  </div>
  <div class='item-info item-text'>
    <div class='wayfinding'>
      <a class="wayfinding--breadcrumb icon-home" href="<?= $site->siteUrl(); ?>"><span class="screen-reader-text">Home</span></a>
      <span>></span>
      <a class="wayfinding--breadcrumb" href="<?= $site->siteUrl(); ?>">Discover</a>
      <?php
        /** @var Omeka\Api\Representation\ItemSetRepresentation $itemSet */
        $itemSets = $item->itemSets();
      ?>
      <span>></span>
      <?php
        if (count ($itemSets) > 0):
          $firstItemSet = array_shift($itemSets);
      ?>
          <?= sprintf("<a class='wayfinding--breadcrumb key-item-set' href='%s'>%s</a>",$firstItemSet->url(),$firstItemSet->title()) ?>
      <?php endif; ?>
    </div>
    <header>
      <div class="item-label"><?= $label ?></div>
      <?= $this->pageTitle($item->displayTitle(), 1); ?>
    </header>
    <?php if ($item->value('dcterms:alternative')): ?>
      <div class='subtitle'>
        <?= $item->value('dcterms:alternative'); ?>
      </div>
    <?php endif; ?>
    <?php if ($creator): ?>
      <div class='deck'>
        <?= $creator; ?>
      </div>
    <?php endif; ?>


      <div class="container-with-tabs-and-panels">

        <?php if ($hasTranscription): ?>
          <div class="tabs">
            <a class="tab description-tab active-tab">Description</a> |
            <a class="tab info-tab">Transcription</a>
          </div>
        <?php endif; ?>
        <div class="panels">
          <div class="description-panel">
              <p class="description-text">
              <?php $values = $item->value('dcterms:description', ['all' => true]); foreach ($values as $value) { echo $value->asHtml(); }?>
            </p>
            <div class='key-metadata'>
              <div class='metadata-list metadata-list-top'>
                <?php
                // Display key terms
                foreach(array_intersect_key($item->values(),$keyTerms) as $term => $propertyData):
                  if (!empty($propertyData['values'][0])):
                    printf("<div class='property' data-term='%s'>\n",$term);
                    printf("   <div class='metadata-label'>%s</div>",!empty($propertyData['alternate_label']) ? $propertyData['alternate_label'] : $keyTerms[$term]);
                    print ("    <div class='values'>");
                    /** @var Omeka\Api\Representation\ValueRepresentation $value */
                    foreach($propertyData['values'] as $value)
                      if($value->isPublic()):

                        $url = $searchHelper->getFacetedSearchUrl($value);
                        printf("       <div class='value'><a href='%s'>%s</a></div>",$url,$value);
                      endif;
                    print ("    </div>");
                    print ("</div>");
                  endif;
                endforeach;
                ?>
                <div class="property">
                  <?php $itemSets = $item->itemSets(); ?>
                  <?php if (count($itemSets) > 0): ?>
                    <div class="label label-item-info metadata-label"><?php echo $translate(
                        "Item sets"
                      ); ?></div>
                    <?php foreach ($itemSets as $itemSet): ?>
                      <div class="value"><a class="item-set-link-top" href="<?php echo $escape(
                          $itemSet->url()
                        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
                    <?php endforeach; ?>
                  <?php endif; ?>
                </div>
              </div>
            </div>
            <div class='rights'>
              <div class="metadata-label">Download</div>
              <?php if ($item->primaryMedia()):  // Download item ?>
                <?= $partial('agile-item/download-item-block', [
                  'item' => $item,
                ]) ?>
              <?php endif; ?>
            </div>
            <?php if (!empty($item->value("dcterms:rights"))): ?>
              <div class='rights-statement'>
                <p class="metadata-label">Rights Statement</p>
                <p class="metadata-value"><?php echo($item->value('dcterms:rights')); ?></p>
              </div>
            <?php endif; ?>
          </div>
          <?php if ($hasTranscription): ?>
            <div class="transcription-panel">
              <p class="metadata-label">Transcription of this Item</p>
                <?php if (!empty($item->value("vra:text"))): ?>
                <?php echo $item->value("vra:text"); ?>
              <?php else: ?>
                <p class="no-transcription">Transcription not available.</p>
              <?php endif; ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
  </div>
</div>
<div class='item-metadata-block reversed'>
  <header>
    <h2>Full Metadata</h2>
  </header>

  <div class='metadata-list'>
    <?php echo $item->displayValues(); ?>
    <div class="property">
        <?php $itemSets = $item->itemSets(); ?>
        <?php if (count($itemSets) > 0): ?>
        <div class="metadata-label"><?php echo $translate("Item sets"); ?></div>
        <?php foreach ($itemSets as $itemSet): ?>
        <div class="value"><a class="item-set-link" href="<?php echo $escape(
          $itemSet->url()
        ); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
        <?php endforeach; ?>
        <?php endif; ?>
    </div>
  </div>

  <?php
    $page = $this->params()->fromQuery("page", 1);
    $property = $this->params()->fromQuery("property");
    //$subjectValues = $item->displaySubjectValues($page, 25, $property);
    $subjectValues = null; //@todo: getting error
  ?>
  <?php if ($subjectValues): ?>
    <div id="item-linked">
    <h3><?php echo $translate("Linked resources"); ?></h3>
    <?php echo $subjectValues; ?>
    </div>
  <?php endif; ?>
</div>
<?php if (count($relatedItems) > 0): ?>
  <div id="related-items">
    <h2>Related Items</h2>
    <ul class="masonry-grid cards grid">
      <?php foreach ($relatedItems as $relatedItem): ?>
        <?= $partial('agile-item/card', [
          'item' => $relatedItem,
          'containerElement' => 'li'
        ]) ?>
      <?php endforeach; ?>
    </ul>
  </div>
<?php endif; ?>
<!-- END agile-theme-tools/agile-item/show.phtml -->
