<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$partial = $plugins->get('partial');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Class'),
        'value' => 'resource_class_label'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>
<!-- BEGIN omeka/site/item/browse.phtml -->
<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 2); ?>
    <h3><?php echo $translate('Item set'); ?></h3>
    <div class="metadata">
        <?php echo $itemSet->displayValues(); ?>
    </div>
    <div class="item-set-items">
    <?php echo '<h3>' . $escape($translate('Items')) . '</h3>'; ?>
<?php else: ?>
    <div class="explore">
        <h1>Browse collection</h1
        <div id="search"><?php echo $this->partial('common/search-form'); ?>
          <div class="advanced-search">
            <?php echo $this->hyperlink($translate('Use advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true)); ?>
          </div>
        </div>
    </div>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>


<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php foreach ($items as $item): ?>
  <?=
  $partial('agile-item/card', [
    'containerElement' => 'li',
    'cardStyle' => 'list-item',
    'item' => $item
  ]) ?>
<?php endforeach; ?>
</ul>
<?php echo ($itemSetShow) ? '</div>' : ''; ?>
<?php //$this->trigger('view.browse.after'); ?>
<div class="browse-controls">
  <?php echo $this->pagination(); ?>
</div>
<!-- END omeka/site/item/browse.phtml -->
