<!-- BEGIN TEMPLATE: /common/block-layout/file.phtml -->
<div class="<?php echo $this->alignmentClass . ' ' . $this->thumbnailType; ?> file">
  <div class="attachments">
    <?php foreach($this->attachments as $attachment): ?>
    <div class="item resource card">
      <?php $item = $attachment->item(); 
      
      if ($item):?>
        <?php 
          $media = $attachment->media() ?: $item->primaryMedia();
          if ($media):
              echo $media->render([
                  'thumbnailType' => $thumbnailType,
                  'link' => $link,]); 
          endif;
        ?>
      <div class="media-embed-info item-info">  
        <?php 
          $institution = $item->value('vra:placeOfRepository'); 
          if ($institution):?>
            <div class="item-label"><?php echo $institution; ?></div>
          <?php endif; ?>
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
          <h4 class="item-title"><?php echo $item->link($item->displayTitle()); ?></h4>
            <?php elseif ($showTitleOption == 'file_name'): ?>
          <h4 class="item-title"><?php echo $media->displayTitle(); ?></h4>
        <?php endif; ?>
        <?php $textSummary = $this->plugin('textSummary')?>
        <div class="item-description"><?php echo $textSummary->summarize($this->plugin('escapeHtml')($this->siteSetting('browse_body_property_term') ? $item->value($this->siteSetting('browse_body_property_term')) : $item->displayDescription()),600); ?></div>
        
        <?php $caption = $attachment->caption(); 
        if ($caption): ?>
          <div class="caption item-description"><?php echo $caption; ?></div>
        <?php endif; ?>
        <div class="item-link">
          <?php echo $item->link($item->value($this->siteSetting('browse_heading_property_term', 'Find Out More'), ['default' => $this->plugin('translate')('Find Out More')])); ?> 
        </div>
      <?php endif; ?>
      </div>
     <?php endforeach; ?>
    </div>
  </div>
</div>
<!-- END TEMPLATE: /common/block-layout/file.phtml -->



