<div class="item-showcase card">
  <?php foreach ($attachments as $attachment): ?>
    <div class="item resource">
      <?php $item = $attachment->item();
        if ($item):?>
      <div class="image-container">
        <?php $media = $attachment->media() ?: $item->primaryMedia();
          if ($media):
          echo $item->linkRaw($this->thumbnail($media, $this->thumbnailType));
          endif;?>
      </div>

      <div class="container-with-tabs-and-panels">
        <?php $showTitleOption = $this->showTitleOption; ?>
        <?php if ($showTitleOption == 'item_title'): ?>
        <div class="panels wrapper">
          <div class="item-info">
         
          <div class=download-icons>
            <p>Download</p>
              <div class='download-item'>
                <?php
                  // See https://stackoverflow.com/a/64719808/16534002
                  $primary_media = $item->primaryMedia()->originalUrl();
                  $url_parts = $primary_media ? explode('/',$primary_media) : [];
                  $file_name = array_pop($url_parts);
                  $dl_attribute = !empty($file_name) ? ' download="'. $file_name .'"' : '';
                  
                  $metadata_file_name = "metadata-" . urlencode(strtolower(str_replace(' ','_',$item->title()))) .".json";
                ?>
                <a class='icon-ui' title="Download item" href='<?php echo $item
                  ->primaryMedia()
                  ->originalUrl(); ?>' <?php echo $dl_attribute; ?>>
                   <span class="screen-reader-text">Download item</span>
                  Item
                </a>
              </div>
              <div class='download-metadata'>
                <a class='icon-ui'  title="Download metadata" target="_blank" type='application/json' href='<?php echo $item->apiUrl(); ?>' download='<?php echo $metadata_file_name; ?>'>
                <span class="screen-reader-text">Download metadata</span>
                Metadata
                </a>
              </div>
            </div> 


            <?php $institution = $item->value('vra:placeOfRepository'); if ($institution):?>
            <div class="item-label"><?php echo $institution; ?></div>
            <?php endif; ?>

            <h3 class="item-title"><?php echo $item->link($item->displayTitle()); ?></h3>
            <?php elseif ($showTitleOption == 'file_name'): ?>
            <h3 class="item-title"><?php echo $media->displayTitle(); ?></h3>
            <?php endif; ?>
           
              <?php $textSummary = $this->plugin('textSummary')?>
            <div class="item-description"><?php echo $textSummary->summarize($this->plugin('escapeHtml')($this->siteSetting('browse_body_property_term') ? $item->value($this->siteSetting('browse_body_property_term')) : $item->displayDescription()),600); ?></div>
           
            <?php $caption = $attachment->caption();
              if ($caption):?>
            <div class="caption item-description"><?php echo $caption; ?></div>
              <?php endif; ?>
            
            <div class="item-link">
        <?php echo $item->link($item->value($this->siteSetting('browse_heading_property_term', 'Find Out More'), ['default' => $this->plugin('translate')('Find Out More')])); ?> <span>></span>
      </div>
          </div>
        </div>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
    </div>

</div>
