<?php
  $translate = $this->plugin('translate');
  $partial = $this->plugin('partial');
?>
<!-- BEGIN TEMPLATE: /common/block-layout/item-listing.phtml -->
<div id="block-<?php echo $this->blockId; ?>" class="item-listing region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <?php if ($this->hasTitle || $this->hasIntroduction): ?>
        <div class='title-area'>
            <?php if ($this->hasTitle): ?>
                <h2><?php echo $this->title; ?></h2>
            <?php endif; ?>
            <?php if ($this->hasIntroduction): ?>
                <div class='block-introduction'>
                    <?php echo $this->introduction; ?>
                </div>
            <?php endif; ?>
            <?php if ($this->hasButton): ?>
                <?php printf('<button class="reversed"><a href="%s" alt="%s">%s</a>',$this->buttonPath,$this->buttonText,$this->buttonText); ?></button>
            <?php endif; ?>
        </div>
    <?php endif; ?>
    <ul class="listing masonry-grid resource-list search-results-list grid">
          <?php
          $headingTerm = $this->siteSetting('browse_heading_property_term');
          $bodyTerm = $this->siteSetting('browse_body_property_term');
          foreach ($attachments as $attachment):
          ?>
            <?= $partial('agile-item/card', [
              'item' => $attachment->item(),
              'containerElement' => 'li'
            ]) ?>
          <?php endforeach; ?>
    </ul>

</div>
<!-- END TEMPLATE: /common/block-layout/item-listing.phtml -->