<!-- BEGIN TEMPLATE common/block-layout/section-list-cards -->
<div id="block-<?= $this->blockId; ?>" class="section-list section-list-cards region <?= $this->regionClass; ?> <?= $this->classes ?>" data-target-region-id="<?= $this->targetID; ?>">
    <?php if ($this->hasTitle): ?>
        <h2><?= $this->title; ?></h2>
    <?php endif; ?>
    <?php if ($this->hasIntroduction): ?>
        <div class='block-introduction'>
            <?= $this->introduction; ?>
        </div>
    <?php endif; ?>
    <?php if ($this->hasPages): ?>
    <div class="card-container">
        <ul class="cards grid">
            <?php foreach($this->pages as $page): ?>
                <li class='item'>
                    <a title="See <?= $page['o:title']; ?>" class="card" href='<?= $page['o:url']; ?>'>
                        <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('representativeImage',$page['embeddedBlocks'])): ?>
                            <?= $page['embeddedBlocks']['representativeImage'][0]; ?>
                        <?php endif; ?>
                        <div class="item-info">
                            <?php if (!empty($this->cardLabel)): ?>
                              <div class="item-label"><?= $this->cardLabel ?></div>
                            <?php endif; ?>
                            <h3 class="item-title"><?= $page['o:title']; ?></h3>
                            <div class="item-description">
                                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('byline',$page['embeddedBlocks'])): ?>
                                    <?= $page['embeddedBlocks']['byline'][0]; ?>
                                <?php endif; ?>
                                <?php if ($page['hasEmbeddedBlocks'] && array_key_exists('excerpt',$page['embeddedBlocks'])): ?>
                                    <?= $page['embeddedBlocks']['excerpt'][0]; ?>
                                <?php endif; ?>
                            </div>
                            <div class='more'>View</div>
                        </div>
                    </a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
    <?php endif; ?>
</div>
<!-- END TEMPLATE common/block-layout/section-list-cards -->
