<?php
// Variables also available:
// $labelText
// $subtitle
// $buttonText
$plugins = $this->getHelperPluginManager();
$partial = $this->plugin('partial');
$thumbnailer = $plugins->get('thumbnail');

?>
<div id="block-<?php echo $this->blockId; ?>" class="slideshow-block slideviewer-container region <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?>">
    <div class='slide-container'>
          <slide-viewer class="<?php echo $hasAudioAttachment ? 'slideshow-with-audio' : ''; ?>" option-slidesPerRow='<?php echo $optionSlidesPerRow; ?>' option-autoplay='<?php echo $optionAutoPlay; ?>' option-fade='<?php echo $optionFade; ?>' integratedcontrols>
            <div slot='slides'>
                  <?php if ($useTitleSlide): ?>
                      <slide-item class="title-slide">
                          <div slot='slide-content'>
                              <?php
                                  if ($titleSlideMedia):
                                      echo $thumbnailer($titleSlideMedia, $thumbnailType);
                                  endif;?>
                          </div>
                          <div slot='slide-caption'>
                            <?php
                                  if ($titleSlideMedia):
                                    echo $thumbnailer($titleSlideMedia, $thumbnailType);
                                  endif;?>
                              <div class="slide-title-content">

                                  <?php if (!empty($labelText)): ?>
                                      <div class='item-label'><?php echo $labelText; ?></div>
                                  <?php endif; ?>
                                  <?php if (!empty($titleSlideTitle)): ?>
                                      <h2><?php echo $titleSlideTitle; ?></h2>
                                  <?php endif; ?>
                                  <?php if (!empty($subtitle)): ?>
                                      <div class='deck'><?php echo $subtitle; ?></div>
                                  <?php endif; ?>
                                  <?php if (!empty($titleSlideIntro)): ?>
                                      <?php echo $titleSlideIntro; ?>
                                  <?php endif; ?>
                                  <?php if (!empty($buttonText)): ?>
                                    <div class="arrow-container">
                                    <div class='slickNext next-slide'>
                                       <h2> <?php echo $buttonText; ?></h2>
                                        <img class="slider-arrow" alt='Next Slide' src=<?php echo $this->assetUrl('img/svg/icons/arrow-right-icon.svg'); ?>>
                                        <img class="slider-arrow-black" alt='Next Slide' src=<?php echo $this->assetUrl('img/svg/icons/arrow-right-icon-neutral.svg'); ?>>
                                    </div>

                                  </div>
                                  <?php endif; ?>
                              </div>
                          </div>
                      </slide-item>
                  <?php endif; ?>

                  <?php /** @var Omeka\Api\Representation\SiteBlockAttachmentRepresentation $attachment **/ ?>
                  <?php foreach ($attachments as $attachment): ?>
                      <div class="slide-item-content" slot="slide-content">
                        <?php
                        /** @var Omeka\Api\Representation\ItemRepresentation $item */
                        // var_dump("Media ID: " . $attachment->media()->id());
                        $item = $attachment->item();
                        $media = $attachment->media() ?: $item->primaryMedia();
                        ?>
                        <?= $partial('agile-item/slide-item', [
                          'item' => $item,
                          'media' => $attachment->media() ?: $item->primaryMedia(),
                          'caption' => $attachment->caption() ?: $item->displayDescription(),
                          'imageSize' => 'large'
                        ]) ?>
                        <?php if (!empty($attachment->caption())): ?>

                        <?php endif; ?>


                      </div>

                  <?php endforeach; ?>
              </div>
              <?php if($hasAudioAttachment): ?>
                  <div class="audio-controls">
                      <div class="audio-player">
                          <?php echo $audioAttachment->media()->render(); ?>
                          <div class="audio-message">
                              <a href=='#' class='audio-text-play-control' title='Play audio' data-playbtnmsg='Play audio slideshow' data-stopbtnmsg='Pause audio slideshow'>Play audio slideshow.</a>
                          </div>
                      </div>
                      <?php if ($audioAttachment->caption()): ?>
                          <div class="audio-caption">
                              <?php echo $audioAttachment->caption(); ?>
                          </div>
                      <?php endif; ?>
                  </div>
              <?php endif; ?>
          </slide-viewer>
    </div>
</div>
