<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation $searchPage
 * @var \AdvancedSearch\Query $query
 * @var \AdvancedSearch\Response $response
 * Options:
 * @var ?\Omeka\Api\Representation\ItemSetRepresentation $itemSet
 */

if (!isset($response) || empty($searchPage->subSetting('facet', 'facets'))) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');

$facets = $response->getFacetCounts();
$activeFacets = $response->getActiveFacets();

// Don't display facet groups without facet elements.
$facets = array_filter($facets);

$displayActive = (bool) $searchPage->subSetting('facet', 'display_active', true);

$isFacetModeButton = $searchPage->subSetting('facet', 'mode') !== 'link';
$displayFacetButton = $isFacetModeButton && !empty($facets);
$displayButton = $displayFacetButton ? $searchPage->subSetting('facet', 'display_button', 'above') : 'none';

$facetActive = $plugins->get('facetActive');
$facetLabel = $plugins->get('facetLabel');
// Facet checkbox can be used in any case anyway, the js checks it.
$facetElements = $isFacetModeButton ? $plugins->get('facetCheckboxes') : $plugins->get('facetLinks');
$facetSelect = $plugins->get('facetSelect');

// Don't display facets for item sets when browsing an item set.
if (!empty($itemSet)) {
    unset($facets['item_set_id']);
    unset($activeFacets['item_set_id']);
}

$options = $searchPage->setting('facet', []);
?>

<!-- FACETS TEMPLATE BEGIN search/facets.phtml -->

    <h3><?= $translate('Filter results') ?></h3>

    <!-- Suppress active facets (moved to search.phtml)

    <?php if ($displayActive && count($activeFacets)): ?>
    <h4><?= $translate('Active facets') ?></h4>
    <ul class="search-facets-active">
        <?php foreach ($activeFacets as $name => $facetValues) foreach ($facetValues as $facetValue): ?>
        <li><?= $facetActive($name, ['value' => $facetValue, 'count' => null], $options) ?></li>
        <?php endforeach; ?>
    </ul>
    <?php endif; ?>

    -->

    <form id="form-facets">

        <?php if ($displayFacetButton): ?>
        <?= $this->hiddenInputsFromFilteredQuery(null, ['facet', 'page', 'limit', 'offset', 'per_page']) ?>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'above' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-top">
            <button type="submit"><?= $translate('Apply filters') ?></button>
        </div>
        <?php endif; ?>

        <?php if (empty($facets) && empty($activeFacets)): ?>
        <p><?= $translate('No filters.') ?></p>
        <?php else: ?>
        <ul class="search-facets-list">
            <?php foreach ($facets as $name => $facetValues): ?>
                <?php
                    $label = $facetLabel($name) == 'place of repository' ? 'Institution' : $facetLabel($name);
                    // $open = $label == 'Institution';
                    $open = true;
                    $facetClass = urlencode(strtolower(str_replace(' ','-',$label)));
                ?>
            <li class="search-facet <?= $facetClass ?>">
                <details <?= $open ? 'open' : '' ?>>
                    <summary><?= $translate($label) ?></summary>
                    <div class='options'>
                        <?php if (($options['facets'][$name]['type'] ?? 'Checkbox') === 'Select'): ?>
                        <?= $facetSelect($name, $facetValues, $options) ?>
                        <?php else: ?>
                        <?= $facetElements($name, $facetValues, $options) ?>
                    </div>
                    <button class='more-options' tabindex="0">More options</button>
                </details>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
        </ul>
        <?php endif; ?>

        <?php if ($displayFacetButton && ($displayButton === 'below' || $displayButton === 'both')): ?>
        <div class="apply-facets apply-facets-bottom">
            <button type="submit"><?= $translate('Apply filters') ?></button>
        </div>
        <?php endif; ?>

    </form>
<!-- FACETS TEMPLATE END -->
