<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $name
 * @var array $facetValues With value, count, active, label and url when needed.
 * @var array $options
 * @var array|null $tree For item sets tree or thesaurus. Don't contain data from item sets not in the site.
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$isFacetModeDirect = in_array($options['mode'] ?? null, ['link', 'js']);
$displayCount = !empty($options['display_count']);

$isTree = is_array($tree);

?>

<ul class="facet-items">
    <?php
    foreach ($facetValues as $facetValue):
        $escapedValue = $escapeAttr($facetValue['value']);
        $escapedId = $name . '[]' . $escapedValue;

        /* The item set’s label is empty when an item set id is passed to the checkbox facet.
         * This conditional works in tandem with logic in the facets-list.phtml, which adds an extra facet
         * value key with the Item Set’s display name. Adding a key should keep it backwards compatible if this is fixed
         * (or properly configured, if that's the issue).
         */

        $facetValue['label'] = !empty($facetValue['label']) ? $facetValue['label'] : (array_key_exists('item_set_label',$facetValue) ? $facetValue['item_set_label'] : $facetValue['label']);
        $label = $displayCount
            ? sprintf('<span>%s <span class="count">(%d)</span></span>', $escape($facetValue['label']),  $facetValue['count'])
            : $escape($facetValue['label']);
        $treeVal = $isTree ? $tree[$facetValue['value']] ?? null : null;
        $treeValAttrs = $treeVal ? sprintf(' data-value="%s" data-parent="%s" data-level="%s"', $treeVal['id'], $treeVal['parent'], $treeVal['level']) : '';
    ?>
    <li class="facet-item <?= $facetValue['active'] ? 'active' : 'inactive' ?>"<?= $treeValAttrs ?>>
        <input type="checkbox" name="<?= "facet[$name][]" ?>" id="<?= $escapedId ?>" value="<?= $escapedValue ?>"<?= $isFacetModeDirect ? ' data-url="' . $escapeAttr($facetValue['url']) . '"' : '' ?><?= $facetValue['active'] ? ' checked="checked"' : '' ?>/>
        <label for="<?= $escapedId ?>"><?= $label ?></label>
    </li>
    <?php endforeach; ?>
</ul>
