<?php
/**
 * @file card.phtml
 * @description Displays a card view for a particular item. Use $this->plugin('cardViewer')->getCard($item) to invoke.
 * @var /Laminas/View/View $this
 * @var $containerElement Wrapping element can be passed to card via the View Helper
 * @var /Omeka/Api/Representation/ItemRepresentation $item
 * @var $resource
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$plugins = $this->getHelperPluginManager();
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;

try {
  $textSummary = $this->plugin('textSummary');
} catch (Exception $e)  {
  $textSummary = null;
}
$thumbnailer = $plugins->get('thumbnail');

$containerElement = isset($containerElement) ? $containerElement : "div";
$this->classes = isset($this->classes) ? $this->classes : '';
if (strpos($this->classes, 'card') === false) {
  $this->classes .= " card";
}

$bodyTerm = $this->siteSetting('browse_body_property_term');
$viewItemPageLabelTerm  = $this->siteSetting('browse_view_item_page_term');
$viewItemPageLabel = $viewItemPageLabelTerm ? $item->value($viewItemPageLabelTerm, ['default' => $translate('View')]) : 'View';

$untitled = $translate('[Untitled]');
$thumbnailSize = 'large';

$contentType = [];

if ($item || $resource):

$cardMode = get_class($item);

// Defaults

$year = '';
$resourceClassLabel = $cardMode ? 'Item' : '';
$label = $resourceClassLabel;
$creator = '';
$resourceIndicator = '';

$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');



$url = '';
$heading = '';

switch($cardMode) {
  case 'Omeka\Api\Representation\ItemRepresentation':

    // Item values

    $url = $item->url();
    $altText = $item->value('vra:caption') ? $item->value('vra:caption') : $item->value('dcterms:description');
    $label = 'Item';
    $resourceClassName = "resource-". urlencode(strtolower(str_replace(' ','-',$label)));

    $year = !empty($item->value('dcterms:temporal')) && is_array($item->value('dcterms:temporal')) && count($item->value('dcterms:temporal')) > 0 ? date('Y',$item->value('dcterms:temporal')[0]) : null;
    $label = $resourceClassLabel . ($year ? " {$year}" : '');
    $creator = $item->value('dcterms:creator');

    if (method_exists($item,'resourceClass') && $item->resourceClass() !== null) {
      $resourceClassLabel = $item->resourceClass()->label();
      $resourceIndicator = "resource-id-" . $item->resourceClass()->id();
    }

    $thumbnail = !empty($altText) ? $this->thumbnail($item, $thumbnailSize,['alt' => $escape(strip_tags($altText)),'class' => "{$resourceIndicator} {$resourceClassName}"]) : $this->thumbnail($item, $thumbnailSize,['class' => "{$resourceIndicator} {$resourceClassName}"]);
    $contentType['value'] = ucfirst(!empty($item->value('dcterms:type')) ? $item->value('dcterms:type') : 'Item');
    $heading = $heading ?? $item->displayTitle();
    $body = $body ?? $item->displayDescription();
    break;

  case 'Omeka\Api\Representation\ItemSetRepresentation':
    $url = $item->url();
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $item->displayTitle(null, $valueLang);
    $header = $escape($heading);
    $thumbnail = $thumbnailer($item, 'large');
    $label = 'Item Set';
    $resourceClassName = "resource-". urlencode(strtolower(str_replace(' ','-',$label)));

    if (empty($body)) {
      $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => $valueLang]) : $item->displayDescription(null, $valueLang);
    }
    break;
  default:
    $url = $item->url();
    $heading = $headingTerm ? $item->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $item->displayTitle(null, $valueLang);
    $header = $escape($heading);
    $thumbnail = $thumbnailer($item, 'large');
    $label = 'Resource';
    $resourceClassName = "resource-". urlencode(strtolower(str_replace(' ','-',$label)));

    if (empty($body)) {
      $body = $bodyTerm ? $item->value($bodyTerm, ['lang' => $valueLang]) : $item->displayDescription(null, $valueLang);
    }




  /*case 'resource'
    $url = $resource->url();
    $thumbnail = '';

    if (method_exists($resource,'getItem') && $item = $this->getItem()) {
      $altText = $item->value('vra:caption') ?? '';
      $thumbnail = !empty($altText) ? $this->thumbnail($item, $thumbnailSize,['alt' => $escape(strip_tags($altText)),'class' => "{$resourceIndicator} {$resourceClassName}"]) : $this->thumbnail($item, $thumbnailSize,['class' => "{$resourceIndicator} {$resourceClassName}"]);
    }

    $contentType['value'] = ucfirst(!empty($resource->value('dcterms:type')) ? $resource->value('dcterms:type') : $resource->resourceName());
    $heading = isset($heading) ? $heading->asHtml() : $escape($resource->displayTitle($untitled, $lang));
    $viewItemPageLabel = $resource->value($viewItemPageLabelTerm, ['default' => $translate('Find Out More')]);
    $body = isset($body) ? $body : (isset($bodyTerm) ? $resource->value($bodyTerm, ['lang' => $langValue]) : '');
    if (strpos($this->classes, 'resources') === false) {
      $this->classes .= " resources";
    }*/
}

$heading_fragment = "“" . substr($heading,0,20) . (strlen($heading > 20) ? "... " : ''). "”";
$cardStyle = isset($cardStyle) ? $cardStyle : 'card';

?>
<!-- BEGIN TEMPLATE: /agile-item/card -->
<<?= $containerElement; ?> class="<?= $cardStyle ?> <?= $this->classes ?>"<?php echo isset($slot) ? " slot={$slot}" : '' ?>>
<a <?= !empty($url) ? 'href="'. $url .'"' : ''; ?>>
  <?php if (!empty($thumbnail)): ?>
    <figure class="item-thumbnail <?= $resourceClassName ?> <?= $resourceClassName ?>">
      <?= $thumbnail ?>
    </figure>
  <?php endif; ?>
  <div class="item-info">
    <div class="item-label"><?= $label ?></div>
    <?php if (!empty($heading)): ?>
      <h3 class="item-title"><?= $heading ?></h3>
    <?php endif; ?>
    <?php if (!empty($creator)): ?>
      <div class="item-sublabel"><?= $creator ?></div>
    <?php endif ?>
    <?php if (!empty($body) && $textSummary): ?>
      <div class="item-description"><?= $textSummary->summarize($escape($body),600); ?></div>
    <?php elseif(!empty($body)):?>
      <div class="item-description"><?= $escape($body); ?></div>
    <?php endif; ?>
    <div class="more"><?= $viewItemPageLabel ?></div>

  </div>
</a>
</<?php print $containerElement; ?> >
<?php endif; ?>
<!-- END TEMPLATE: /agile-item/card -->
