<div class=download-icons>
  <div class='download-item'>
    <?php
    // See https://stackoverflow.com/a/64719808/16534002
    $primary_media = $item->primaryMedia()->originalUrl();
    $url_parts = $primary_media ? explode('/',$primary_media) : [];
    $file_name = array_pop($url_parts);
    $dl_attribute = !empty($file_name) ? ' download="'. $file_name .'"' : '';

    ?>
    <a class='download-link' title="Download item" href='<?= $item
      ->primaryMedia()
      ->originalUrl(); ?>' <?= $dl_attribute; ?>>
      <span class="screen-reader-text">Download item</span>
      Download
      <img class="download-icon" alt='Download Icon'  src=<?= $this->assetUrl('img/svg/icons/download-icon-neutral.svg'); ?>>
    </a>
  </div>
</div>
