<?php
    use Omeka\Api\Representation\ItemRepresentation;

    $translate = $this->plugin('translate');
    $escape = $this->plugin('escapeHtml');
    $plugins = $this->getHelperPluginManager();
    $thumbnailer = $plugins->get('thumbnail');
    $thumbnailSize = 'large';
    $textLimit = $textLimit ?? 600;
    $showTitleOption = $showTitleOption ?? 'item_title';

    try {
      $textSummary = $this->plugin('textSummary');
    } catch (Exception $e)  {
      $textSummary = null;
    }
?>
<!-- BEGIN agile-item/slide-item.phtml -->
<slide-item>
  <?php
    /** @var Omeka\Api\Representation\ItemRepresentation */
    if ($item):
  ?>
      <?php
        /** @var \Omeka\Api\Representation\MediaRepresentation $media */
        $media = $item->primaryMedia();
        $caption = $caption ?? $item->displayDescription();
        $thumbnail = $this->thumbnail($item, $imageSize);

      ?>
      <?php
        if ($media):
      ?>
        <div slot='slide-content'>
          <?php echo $thumbnail; ?>
        </div>
      <?php endif; ?>
      <div slot='slide-caption'>
        <?php if ($showTitleOption == 'item_title'): ?>
          <h3><?php echo $item->link($item->displayTitle()); ?></h3>
        <?php elseif ($showTitleOption == 'file_name'): ?>
          <h3><?php echo $media->displayTitle(); ?></h3>
        <?php endif; ?>
        <?php
          if ($caption):
            echo $caption;
          endif;
        ?>
      </div>
    <?php endif; ?>
</slide-item>
<!-- END agile-item/slide-item.phtml -->
